/*
 * Go Blog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ConfigCopyright struct {

	From int32 `json:"from,omitempty"`

	Company string `json:"company,omitempty"`
}
