/*
 * Go Blog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Author struct {

	Id int32 `json:"id,omitempty"`

	FullName string `json:"fullName"`

	Email string `json:"email"`

	Bio string `json:"bio"`
}
