/*
 * Go Blog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Page struct {

	Slug string `json:"slug,omitempty"`

	Authors []Author `json:"authors,omitempty"`

	Title string `json:"title,omitempty"`

	Excerpt string `json:"excerpt,omitempty"`

	PublishedAt time.Time `json:"publishedAt,omitempty"`
}
