/*
 * Go Blog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Author - Author is an User that can author their posts.
type Author struct {

	// This field is the `sub` claim in the OpenID Connect's JWT. 
	UserId string `json:"userId"`

	FullName string `json:"fullName"`

	Email string `json:"email"`

	Bio string `json:"bio"`
}
