/*
 * Go Blog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Config struct {

	// Blog name, for showing the text in various places, i.e. the Home nav link. 
	BlogName string `json:"blogName,omitempty"`

	// Number of posts on the home page.
	PostsOnHomePage int32 `json:"postsOnHomePage,omitempty"`

	// Number of posts in an archive page, for pagination.
	PostsPerArchivePage int32 `json:"postsPerArchivePage,omitempty"`

	// URL to the banner image that shows when the home page is shared on social platforms. 
	BannerUrl string `json:"bannerUrl,omitempty"`

	// Blog description to use as the description meta for the blog. 
	BlogDescription string `json:"blogDescription,omitempty"`

	Copyright ConfigCopyright `json:"copyright,omitempty"`
}
