/*
 * Go Blog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AuthorAllOf struct {

	FullName string `json:"fullName,omitempty"`

	Email string `json:"email,omitempty"`

	Bio string `json:"bio,omitempty"`
}
