/*
 * Go Blog API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostAllOf struct {

	CoverUrl string `json:"coverUrl,omitempty"`

	LastPostSlug *string `json:"lastPostSlug,omitempty"`

	NextPostSlug *string `json:"nextPostSlug,omitempty"`
}
